### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by greg-hellings** [oasis-roles/rhsm#24]
When re-running this role with arguments like

```yaml
rhsm_repositories:
  disabled:
    - '*'
  enabled:
    - foo
    - bar
```

The role will go ahead and disable all of them, then re-enable them, on every run. Not doing this would be ideal, although I'm not sure if it's possible.
